version: '3.8'
services:
mongo:
image: mongo:6
restart: always
volumes:
- mongo-data:/data/db
ports:
- 27017:27017


api:
build: .
depends_on:
- mongo
environment:
- MONGODB_URI=mongodb://mongo:27017/myapp
- JWT_SECRET=supersecret
ports:
- 8000:8000


volumes:
mongo-data: